Repository CICE-Consortium/CICE, pull requests merged in 2020-02, with the labels that each got.

#392 Add CONTRIBUTING, update README
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
Labels: Documentation

#401 update izumi intel compiler after upgrade
  configuration/scripts/machines/env.izumi_intel
  configuration/scripts/tests/nothread_suite.ts
Labels: Porting, Priority: Medium

#395 update suite.submit script and add new controls and cice.setup option…
  cice.setup
  doc/source/user_guide/ug_testing.rst
Labels: Priority: Low, Scripts, Type: Feature

#410 Iceopen
  cicecore/cicedynB/infrastructure/ice_read_write.F90
Labels: Software Engineering
