Repository CICE-Consortium/CICE, pull requests merged in 2020-08, with the labels that each got.

#507 Moved calculation of sicen and trcrn_bgc to the loop where they are used
  cicecore/shared/ice_init_column.F90
Labels: BGC, Priority: Medium, Type: Bug

#508 deprecate upwind advection
  cicecore/cicedynB/dynamics/ice_transport_driver.F90
  cicecore/cicedynB/general/ice_init.F90
  cicecore/cicedynB/general/ice_step_mod.F90
  configuration/scripts/options/set_nml.alt04
  doc/source/developer_guide/dg_dynamics.rst
  doc/source/science_guide/sg_horiztrans.rst
  doc/source/user_guide/ug_case_settings.rst
Labels: Dynamics, Priority: Medium

#510 doc: correct description of box2001 test
  doc/source/user_guide/ug_case_settings.rst
  doc/source/user_guide/ug_testing.rst
Labels: Documentation

#513 doc: fix 'ice strength' description
  doc/source/cice_index.rst
Labels: Documentation
