Repository CICE-Consortium/CICE, pull requests merged in 2020-05, with the labels that each got.

#435 Use JRA55 for tx1 grid
  cicecore/cicedynB/general/ice_forcing.F90
  configuration/scripts/options/set_nml.tx1
  doc/source/user_guide/ug_case_settings.rst
Labels: Forcing, Priority: High, Testing, Type: Feature

#372 NOAA machine pass of base_suite #155
  .gitignore
  configuration/scripts/cice.batch.csh
  configuration/scripts/cice.launch.csh
  configuration/scripts/machines/Macros.hera_intel
  configuration/scripts/machines/env.hera_intel
  configuration/scripts/machines/env.high_Sierra_gnu
  configuration/scripts/machines/env.phase3_intel
Labels: Porting

#444 update io_pio and io_pio2 for fsd input and output fields
  cicecore/cicedynB/infrastructure/io/io_pio/ice_history_write.F90
  cicecore/cicedynB/infrastructure/io/io_pio/ice_restart.F90
  cicecore/cicedynB/infrastructure/io/io_pio2/ice_history_write.F90
  cicecore/cicedynB/infrastructure/io/io_pio2/ice_restart.F90
Labels: Priority: High, Software Engineering, Type: Bug

#446 Precision
  cicecore/cicedynB/analysis/ice_history_shared.F90
  cicecore/cicedynB/general/ice_init.F90
  cicecore/cicedynB/infrastructure/io/io_binary/ice_history_write.F90
  cicecore/cicedynB/infrastructure/io/io_netcdf/ice_history_write.F90
  cicecore/cicedynB/infrastructure/io/io_pio/ice_history_write.F90
  cicecore/cicedynB/infrastructure/io/io_pio/ice_pio.F90
  cicecore/cicedynB/infrastructure/io/io_pio2/ice_history_write.F90
  cicecore/cicedynB/infrastructure/io/io_pio2/ice_pio.F90
  configuration/scripts/ice_in
  configuration/scripts/options/set_nml.precision8
  configuration/scripts/tests/base_suite.ts
  doc/source/cice_index.rst
  doc/source/user_guide/ug_case_settings.rst
  doc/source/user_guide/ug_implementation.rst
Labels: IO, Type: Feature

#448 scripts: add support for setting `ICE_CPPDEFS` in set_env.* options
  cice.setup
  configuration/scripts/cice.batch.csh
  configuration/scripts/cice.build
  configuration/scripts/cice.settings
  configuration/scripts/parse_namelist.sh
  doc/source/developer_guide/dg_about.rst
  doc/source/developer_guide/dg_driver.rst
  doc/source/developer_guide/dg_dynamics.rst
  doc/source/developer_guide/dg_icepack.rst
  doc/source/developer_guide/dg_scripts.rst
  doc/source/developer_guide/index.rst
  doc/source/intro/about.rst
  doc/source/intro/acknowledgements.rst
  doc/source/intro/copyright.rst
  doc/source/intro/index.rst
  doc/source/intro/quickstart.rst
  doc/source/science_guide/figures/EAP.png
  doc/source/science_guide/figures/albedo.png
  doc/source/science_guide/figures/deparr.png
  doc/source/science_guide/figures/gplot.png
  doc/source/science_guide/figures/triangles.png
  doc/source/science_guide/index.rst
  doc/source/user_guide/figures/extra/distrb_cart_X1_20x24_16.png
  doc/source/user_guide/figures/extra/distrb_cart_X2_20x24_16.png
  doc/source/user_guide/figures/extra/distrb_cart_sqr_20x24_16.png
  doc/source/user_guide/figures/extra/distrb_rake_block_20x24_16.png
  doc/source/user_guide/figures/extra/distrb_rake_lat_20x24_16.png
  doc/source/user_guide/figures/extra/distrb_sfc_lat_20x24_16.png
  doc/source/user_guide/figures/extra/topo2.png
  doc/source/user_guide/figures/extra/topo3.png
  doc/source/user_guide/figures/grid.png
  doc/source/user_guide/figures/histograms.png
  doc/source/user_guide/figures/scorecard.png
  doc/source/user_guide/ug_case_settings.rst
  doc/source/user_guide/ug_running.rst
Labels: Build, Type: Feature

#449 Update NOAA ports, hera and orion
  configuration/scripts/cice.batch.csh
  configuration/scripts/cice.launch.csh
  configuration/scripts/machines/Macros.hera_intel
  configuration/scripts/machines/Macros.high_Sierra_gnu
  configuration/scripts/machines/Macros.orion_intel
  configuration/scripts/machines/Macros.phase3_intel
  configuration/scripts/machines/Macros.theia_gnu
  configuration/scripts/machines/Macros.theia_intel
  configuration/scripts/machines/Macros.theia_pgi
  configuration/scripts/machines/env.hera_intel
  configuration/scripts/machines/env.orion_intel
  configuration/scripts/machines/env.phase2_intel
  configuration/scripts/machines/env.theia_gnu
  configuration/scripts/machines/env.theia_intel
  configuration/scripts/machines/env.theia_pgi
Labels: Porting
