Repository CICE-Consortium/CICE, pull requests merged in 2020-06, with the labels that each got.

#459 Update documentation including qc, debugger, and namelist table
  cicecore/cicedynB/general/ice_init.F90
  cicecore/version.txt
  doc/source/conf.py
  doc/source/developer_guide/dg_about.rst
  doc/source/developer_guide/dg_dynamics.rst
  doc/source/developer_guide/dg_other.rst
  doc/source/master_list.bib
  doc/source/user_guide/ug_case_settings.rst
  doc/source/user_guide/ug_testing.rst
Labels: Documentation

#462 remove INTEL20_WORKAROUND and port to mustang
  cicecore/cicedynB/dynamics/ice_transport_remap.F90
  configuration/scripts/cice.batch.csh
  configuration/scripts/cice.launch.csh
  configuration/scripts/machines/Macros.mustang_intel18
  configuration/scripts/machines/Macros.mustang_intel19
  configuration/scripts/machines/Macros.mustang_intel20
  configuration/scripts/machines/env.izumi_intel
  configuration/scripts/machines/env.mustang_intel18
  configuration/scripts/machines/env.mustang_intel19
  configuration/scripts/machines/env.mustang_intel20
Labels: Porting, Priority: High

#466 add MACHINFO and ENVINFO to env files
  cice.setup
  configuration/scripts/cice.batch.csh
  configuration/scripts/cice.build
  configuration/scripts/cice.launch.csh
  configuration/scripts/cice.settings
  configuration/scripts/machines/Macros.loft_gnu
  configuration/scripts/machines/Macros.thunder_intel
  configuration/scripts/machines/env.badger_intel
  configuration/scripts/machines/env.banting_gnu
  configuration/scripts/machines/env.banting_intel
  configuration/scripts/machines/env.cesium_intel
  configuration/scripts/machines/env.cheyenne_gnu
  configuration/scripts/machines/env.cheyenne_intel
  configuration/scripts/machines/env.cheyenne_pgi
  configuration/scripts/machines/env.conda_linux
  configuration/scripts/machines/env.conda_macos
  configuration/scripts/machines/env.conrad_cray
  configuration/scripts/machines/env.conrad_gnu
  configuration/scripts/machines/env.conrad_intel
  configuration/scripts/machines/env.conrad_pgi
  configuration/scripts/machines/env.cori_intel
  configuration/scripts/machines/env.daley_gnu
  configuration/scripts/machines/env.daley_intel
  configuration/scripts/machines/env.fram_intel
  configuration/scripts/machines/env.gaffney_gnu
  configuration/scripts/machines/env.gaffney_intel
  configuration/scripts/machines/env.gordon_cray
  configuration/scripts/machines/env.gordon_gnu
  configuration/scripts/machines/env.gordon_intel
  configuration/scripts/machines/env.gordon_pgi
  configuration/scripts/machines/env.hera_intel
  configuration/scripts/machines/env.high_Sierra_gnu
  configuration/scripts/machines/env.hobart_intel
  configuration/scripts/machines/env.hobart_nag
  configuration/scripts/machines/env.izumi_gnu
  configuration/scripts/machines/env.izumi_intel
  configuration/scripts/machines/env.izumi_nag
  configuration/scripts/machines/env.izumi_pgi
  configuration/scripts/machines/env.koehr_intel
  configuration/scripts/machines/env.loft_gnu
  configuration/scripts/machines/env.millikan_intel
  configuration/scripts/machines/env.mustang_intel18
  configuration/scripts/machines/env.mustang_intel19
  configuration/scripts/machines/env.mustang_intel20
  configuration/scripts/machines/env.onyx_cray
  configuration/scripts/machines/env.onyx_gnu
  configuration/scripts/machines/env.onyx_intel
  configuration/scripts/machines/env.orion_intel
  configuration/scripts/machines/env.phase3_intel
  configuration/scripts/machines/env.testmachine_intel
  configuration/scripts/machines/env.thunder_intel
  configuration/scripts/machines/env.travisCI_gnu
  configuration/scripts/tests/baseline.script
  configuration/scripts/tests/report_results.csh
  doc/source/user_guide/ug_case_settings.rst
  doc/source/user_guide/ug_running.rst
Labels: Documentation, Testing

#467 Add lcov code coverage tool
  README.md
  cice.setup
  configuration/scripts/cice.batch.csh
  configuration/scripts/cice.build
  configuration/scripts/cice.codecov.csh
  configuration/scripts/cice.launch.csh
  configuration/scripts/cice.lcov.csh
  configuration/scripts/cice.results.csh
  configuration/scripts/cice.run.setup.csh
  configuration/scripts/cice.settings
  configuration/scripts/cice.test.setup.csh
  configuration/scripts/machines/Macros.cheyenne_gnu
  configuration/scripts/machines/Macros.gaffney_gnu
  configuration/scripts/machines/Macros.gordon_gnu
  configuration/scripts/machines/Macros.izumi_gnu
  configuration/scripts/machines/Macros.onyx_gnu
  configuration/scripts/machines/Macros.travisCI_gnu
  configuration/scripts/machines/env.cheyenne_gnu
  configuration/scripts/machines/env.cheyenne_intel
  configuration/scripts/machines/env.cheyenne_pgi
  configuration/scripts/set_version_number.csh
  configuration/scripts/setup_run_dirs.csh
  configuration/scripts/tests/cice_test_codecov.csh
  doc/source/user_guide/ug_case_settings.rst
  doc/source/user_guide/ug_testing.rst
Labels: Testing, Type: Feature

#470 Fix the README badges specifically related to code coverage
  README.md
Labels: Documentation, Type: Feature

#468 verbose diagnostic output for model configuration
  cicecore/cicedynB/general/ice_init.F90
  configuration/scripts/cice.results.csh
  configuration/scripts/options/set_nml.boxdyn
Labels: IO, Type: Feature

#473 Optionally rotate wind/stress from to computational grid (from true north)
  cicecore/cicedynB/general/ice_forcing.F90
  cicecore/cicedynB/general/ice_init.F90
  configuration/scripts/ice_in
  doc/source/cice_index.rst
Labels: Forcing

#463 Allow for read of tlat, tlon, anglet with popgrid
  cicecore/cicedynB/dynamics/ice_transport_driver.F90
  cicecore/cicedynB/general/ice_step_mod.F90
  cicecore/cicedynB/infrastructure/ice_grid.F90
  cicecore/drivers/nuopc/dmi/cice_cap.info
Labels: IO, Type: Feature

#474 Allow for coupling to both nemo and hycom
  cicecore/drivers/nuopc/dmi/CICE_InitMod.F90
Labels: Drivers/coupling

#476 Update lcov and env documentation
  cice.setup
  configuration/scripts/machines/env.cheyenne_gnu
  configuration/scripts/machines/env.conrad_gnu
  configuration/scripts/tests/cice.codecov.csh
  configuration/scripts/tests/cice.lcov.csh
  configuration/scripts/tests/cice.results.csh
  doc/source/user_guide/ug_running.rst
Labels: Documentation, Testing
