Repository CICE-Consortium/CICE, pull requests merged in 2020-12, with the labels that each got.

#535 Revert "deprecate upwind advection (#508)"
  cicecore/cicedynB/dynamics/ice_dyn_shared.F90
  cicecore/cicedynB/dynamics/ice_transport_driver.F90
  cicecore/cicedynB/general/ice_init.F90
  cicecore/cicedynB/general/ice_step_mod.F90
  configuration/scripts/options/set_nml.alt04
  doc/source/developer_guide/dg_dynamics.rst
  doc/source/science_guide/sg_horiztrans.rst
  doc/source/user_guide/ug_case_settings.rst
Labels: Dynamics, Type: Feature

#539 Update timeseries plots to resolve issue with some fields
  configuration/scripts/timeseries.csh
  configuration/scripts/timeseries.py
Labels: Tools

#545 Update readthedocs requirements
  doc/requirements.txt
Labels: Documentation, Testing

#533 Make JRA55 default forcing dataset
  .travis.yml
  configuration/scripts/options/set_env.box2001
  configuration/scripts/options/set_nml.alt01
  configuration/scripts/options/set_nml.box2001
  configuration/scripts/options/set_nml.gbox80
  configuration/scripts/options/set_nml.gx1
  configuration/scripts/options/set_nml.gx1coreii
  configuration/scripts/options/set_nml.gx3
  configuration/scripts/options/set_nml.gx3ncarbulk
  configuration/scripts/options/set_nml.jra55
  configuration/scripts/options/set_nml.jra55_2008
  configuration/scripts/options/set_nml.jra55_gx1
  configuration/scripts/options/set_nml.jra55_gx1_2008
  configuration/scripts/options/set_nml.jra55_gx3
  configuration/scripts/options/set_nml.jra55_gx3_2008
  configuration/scripts/options/set_nml.yi2008
  configuration/scripts/tests/base_suite.ts
  configuration/scripts/tests/decomp_suite.ts
  configuration/scripts/tests/first_suite.ts
  configuration/scripts/tests/io_suite.ts
  configuration/scripts/tests/nothread_quicksuite.ts
  configuration/scripts/tests/nothread_suite.ts
  configuration/scripts/tests/quick_suite.ts
  configuration/scripts/tests/reprosum_suite.ts
  configuration/scripts/tests/travis_suite.ts
Labels: Forcing, Priority: High, Testing

#548 zsal option for testing zsalinity code
  cicecore/cicedynB/analysis/ice_history_bgc.F90
  cicecore/cicedynB/analysis/ice_history_mechred.F90
  cicecore/cicedynB/analysis/ice_history_pond.F90
  configuration/scripts/options/set_nml.zsal
  configuration/scripts/tests/base_suite.ts
Labels: BGC, Icepack, Priority: Medium, Testing
