Repository CICE-Consortium/CICE, pull requests merged in 2021-03, with the labels that each got.

#570 Update Copyright year to 2021
  cicecore/drivers/direct/hadgem3/CICE.F90
  cicecore/drivers/mct/cesm1/CICE_copyright.txt
  cicecore/drivers/nuopc/cmeps/CICE_copyright.txt
  cicecore/drivers/nuopc/dmi/CICE.F90
  cicecore/drivers/standalone/cice/CICE.F90
  doc/source/conf.py
  doc/source/intro/copyright.rst
Labels: Documentation, Priority: Medium

#571 Update LICENSE.pdf
  LICENSE.pdf
Labels: Documentation

#566 Update Time Manager
  cice.setup
  cicecore/cicedynB/analysis/ice_history.F90
  cicecore/cicedynB/analysis/ice_history_shared.F90
  cicecore/cicedynB/general/ice_forcing.F90
  cicecore/cicedynB/general/ice_forcing_bgc.F90
  cicecore/cicedynB/general/ice_init.F90
  cicecore/cicedynB/general/ice_step_mod.F90
  cicecore/cicedynB/infrastructure/comm/mpi/ice_timers.F90
  cicecore/cicedynB/infrastructure/comm/serial/ice_timers.F90
  cicecore/cicedynB/infrastructure/ice_domain.F90
  cicecore/cicedynB/infrastructure/ice_grid.F90
  cicecore/cicedynB/infrastructure/ice_restart_driver.F90
  cicecore/cicedynB/infrastructure/io/io_binary/ice_restart.F90
  cicecore/cicedynB/infrastructure/io/io_netcdf/ice_history_write.F90
  cicecore/cicedynB/infrastructure/io/io_netcdf/ice_restart.F90
  cicecore/cicedynB/infrastructure/io/io_pio2/ice_history_write.F90
  cicecore/cicedynB/infrastructure/io/io_pio2/ice_restart.F90
  cicecore/drivers/mct/cesm1/CICE_InitMod.F90
  cicecore/drivers/mct/cesm1/CICE_RunMod.F90
  cicecore/drivers/mct/cesm1/ice_comp_esmf.F90
  cicecore/drivers/mct/cesm1/ice_comp_mct.F90
  cicecore/drivers/nuopc/cmeps/CICE_RunMod.F90
  cicecore/drivers/nuopc/cmeps/ice_comp_nuopc.F90
  cicecore/drivers/standalone/cice/CICE_InitMod.F90
  cicecore/drivers/standalone/cice/CICE_RunMod.F90
  cicecore/drivers/unittest/calchk/calchk.F90
  cicecore/drivers/unittest/helloworld/helloworld.F90
  cicecore/shared/ice_calendar.F90
  cicecore/shared/ice_init_column.F90
  configuration/scripts/Makefile
  configuration/scripts/cice.build
  configuration/scripts/cice.run.setup.csh
  configuration/scripts/cice.settings
  configuration/scripts/cice_decomp.csh
  configuration/scripts/ice_in
  configuration/scripts/options/set_env.calchk
  configuration/scripts/options/set_env.helloworld
  configuration/scripts/options/set_nml.run10day
  configuration/scripts/options/set_nml.run1day
  configuration/scripts/options/set_nml.run1year
  configuration/scripts/options/set_nml.run2day
  configuration/scripts/options/set_nml.run3day
  configuration/scripts/options/set_nml.run3dt
  configuration/scripts/options/set_nml.run5day
  configuration/scripts/options/set_nml.run60day
  configuration/scripts/options/set_nml.run90day
  configuration/scripts/options/test_nml.restart1
  configuration/scripts/options/test_nml.restart2
  configuration/scripts/tests/base_suite.ts
  configuration/scripts/tests/baseline.script
  configuration/scripts/tests/comparelog.csh
  configuration/scripts/tests/io_suite.ts
  configuration/scripts/tests/quick_suite.ts
  configuration/scripts/tests/test_unittest.script
  configuration/scripts/tests/unittest_suite.ts
  doc/source/cice_index.rst
  doc/source/developer_guide/dg_dynamics.rst
  doc/source/user_guide/ug_case_settings.rst
  doc/source/user_guide/ug_implementation.rst
  doc/source/user_guide/ug_testing.rst
Labels: Documentation, Drivers/coupling, Forcing, Priority: High, Software Engineering, Type: Bug, Type: Feature

#576 use cell-centered ice velocity for high-freq wind stress calculation
  cicecore/cicedynB/general/ice_step_mod.F90
  configuration/scripts/options/set_nml.alt01
  doc/source/developer_guide/dg_forcing.rst
  doc/source/user_guide/ug_case_settings.rst
Labels: Drivers/coupling, Type: Bug

#581 Add machine Compy with intel
  configuration/scripts/cice.batch.csh
  configuration/scripts/cice.launch.csh
  configuration/scripts/machines/Macros.compy_intel
  configuration/scripts/machines/env.compy_intel
Labels: Porting

#578 Fix reading of mixed layer forcing file.
  cicecore/cicedynB/general/ice_forcing.F90
  cicecore/cicedynB/infrastructure/ice_read_write.F90
  configuration/scripts/options/set_nml.ml
  configuration/scripts/tests/base_suite.ts
Labels: Forcing, Type: Bug

#579 Fixes for uninitialized variables (snan testing)
  cicecore/cicedynB/general/ice_flux.F90
  cicecore/cicedynB/infrastructure/comm/mpi/ice_boundary.F90
  cicecore/cicedynB/infrastructure/comm/serial/ice_boundary.F90
  cicecore/cicedynB/infrastructure/ice_blocks.F90
  cicecore/cicedynB/infrastructure/ice_grid.F90
  cicecore/cicedynB/infrastructure/ice_restoring.F90
  cicecore/drivers/standalone/cice/CICE_RunMod.F90
  cicecore/shared/ice_init_column.F90
  cicecore/shared/ice_spacecurve.F90
  configuration/scripts/machines/Macros.banting_intel
  configuration/scripts/machines/Macros.cheyenne_gnu
  configuration/scripts/machines/Macros.cheyenne_intel
  configuration/scripts/machines/Macros.daley_intel
  configuration/scripts/machines/Macros.gaffney_intel
  configuration/scripts/machines/Macros.koehr_intel
  configuration/scripts/machines/Macros.mustang_intel18
  configuration/scripts/machines/Macros.mustang_intel19
  configuration/scripts/machines/Macros.mustang_intel20
  configuration/scripts/machines/Macros.onyx_intel
  configuration/scripts/machines/env.cheyenne_gnu
  configuration/scripts/machines/env.cheyenne_intel
  configuration/scripts/machines/env.cheyenne_pgi
  configuration/scripts/tests/decomp_suite.ts
Labels: Build, Software Engineering, Testing, Type: Bug

#582 Add JRA55 dataset tool and documentation
  configuration/tools/cice4_restart_conversion/convert_restarts.f90
  configuration/tools/jra55_datasets/interp_jra55_ncdf_bilinear.py
  configuration/tools/jra55_datasets/make_forcing.csh
  doc/source/developer_guide/dg_scripts.rst
  doc/source/developer_guide/dg_tools.rst
  doc/source/developer_guide/index.rst
  doc/source/user_guide/ug_running.rst
  doc/source/user_guide/ug_testing.rst
Labels: Documentation, Tools
