Repository CICE-Consortium/CICE, pull requests merged in 2021-04, with the labels that each got.

#587 Fix 'max_blocks' estimation and add checks
  cicecore/cicedynB/infrastructure/ice_blocks.F90
  cicecore/cicedynB/infrastructure/ice_domain.F90
  cicecore/shared/ice_distribution.F90
  configuration/scripts/ice_in
  configuration/scripts/options/set_nml.debugblocks
  doc/source/user_guide/ug_case_settings.rst
  doc/source/user_guide/ug_implementation.rst
Labels: Documentation, Software Engineering, Type: Bug

#593 Updates for RASM
  cicecore/cicedynB/infrastructure/ice_grid.F90
  cicecore/drivers/mct/cesm1/CICE_RunMod.F90
  cicecore/drivers/mct/cesm1/ice_comp_esmf.F90
  cicecore/drivers/mct/cesm1/ice_comp_mct.F90
  cicecore/drivers/mct/cesm1/ice_prescribed_mod.F90
  cicecore/drivers/nuopc/cmeps/CICE_RunMod.F90
  cicecore/drivers/nuopc/cmeps/ice_comp_nuopc.F90
  cicecore/drivers/nuopc/cmeps/ice_prescribed_mod.F90
Labels: Drivers/coupling

#596 Update onyx batch settings
  configuration/scripts/cice.batch.csh
Labels: Porting
