Repository CICE-Consortium/CICE, pull requests merged in 2021-05, with the labels that each got.

#600 Add `iceruf` to namelist
  cicecore/cicedynB/general/ice_init.F90
  configuration/scripts/ice_in
  doc/source/cice_index.rst
  doc/source/user_guide/ug_case_settings.rst
Labels: Icepack, Type: Feature

#602 Update testing, in particular for diagnostics and decompositions
  cicecore/cicedynB/analysis/ice_diagnostics.F90
  cicecore/cicedynB/dynamics/ice_transport_driver.F90
  cicecore/cicedynB/general/ice_flux.F90
  cicecore/cicedynB/general/ice_forcing.F90
  cicecore/cicedynB/general/ice_init.F90
  cicecore/cicedynB/infrastructure/ice_domain.F90
  cicecore/drivers/direct/hadgem3/CICE.F90
  cicecore/drivers/direct/hadgem3/CICE_FinalMod.F90
  cicecore/drivers/mct/cesm1/CICE_FinalMod.F90
  cicecore/drivers/nuopc/cmeps/CICE_FinalMod.F90
  cicecore/drivers/nuopc/dmi/CICE.F90
  cicecore/drivers/nuopc/dmi/CICE_FinalMod.F90
  cicecore/drivers/standalone/cice/CICE.F90
  cicecore/drivers/standalone/cice/CICE_FinalMod.F90
  cicecore/drivers/standalone/cice/CICE_RunMod.F90
  cicecore/drivers/standalone/cice/CICE_RunMod.F90_debug
  cicecore/drivers/unittest/calchk/calchk.F90
  cicecore/shared/ice_distribution.F90
  cicecore/shared/ice_spacecurve.F90
  configuration/scripts/cice_decomp.csh
  configuration/scripts/ice_in
  configuration/scripts/options/set_nml.alt03
  configuration/scripts/options/set_nml.alt05
  configuration/scripts/options/set_nml.alt06
  configuration/scripts/options/set_nml.bgcz
  configuration/scripts/options/set_nml.bigdiag
  configuration/scripts/options/set_nml.boxadv
  configuration/scripts/options/set_nml.boxnodyn
  configuration/scripts/options/set_nml.boxrestore
  configuration/scripts/options/set_nml.boxslotcyl
  configuration/scripts/options/set_nml.dspiralcenter
  configuration/scripts/options/set_nml.dwghtfile
  configuration/scripts/options/set_nml.gbox180
  configuration/scripts/tests/base_suite.ts
  configuration/scripts/tests/baseline.script
  configuration/scripts/tests/decomp_suite.ts
  configuration/scripts/tests/io_suite.ts
  configuration/scripts/tests/nothread_suite.ts
  doc/source/cice_index.rst
  doc/source/user_guide/ug_case_settings.rst
  doc/source/user_guide/ug_implementation.rst
  doc/source/user_guide/ug_running.rst
  doc/source/user_guide/ug_troubleshooting.rst
Labels: Software Engineering, Testing, Type: Bug

#604 Update coverage tool to manually filter some Fortran90 continuation lines
  cice.setup
  cicecore/cicedynB/dynamics/ice_dyn_evp.F90
  configuration/scripts/tests/lcov_modify_source.sh
  doc/source/user_guide/ug_testing.rst
Labels: Software Engineering, Testing
