Repository CICE-Consortium/CICE, pull requests merged in 2022-08, with the labels that each got.

#744 Change visc_method default to avg_zeta
  cice.setup
  cicecore/cicedynB/general/ice_init.F90
  configuration/scripts/ice_in
  configuration/scripts/options/set_nml.alt07
  doc/source/cice_index.rst
  doc/source/user_guide/ug_case_settings.rst
Labels: Dynamics

#745 cice.setup: allow command line to override suite options
  cice.setup
  doc/source/user_guide/ug_testing.rst
Labels: Testing, Scripts

#749 ice_grid: do call 'gridbox_verts' for rectangular grids
  cicecore/cicedynB/infrastructure/ice_grid.F90
Labels: Software Engineering, Grids

#751 Update ECCC machine files
  configuration/scripts/machines/env.gpsc3_intel
  configuration/scripts/machines/env.ppp5_intel
  configuration/scripts/machines/env.ppp6_gnu
  configuration/scripts/machines/env.ppp6_gnu-impi
  configuration/scripts/machines/env.ppp6_intel
  configuration/scripts/machines/env.ppp6_intel19
  configuration/scripts/machines/env.robert_intel
  configuration/scripts/machines/env.underhill_intel
Labels: Porting

#752 ice_calendar: zero-initialize 'nstreams'
  cicecore/shared/ice_calendar.F90
Labels: Software Engineering, Analysis

#746 Added dxgrow, dygrow to facilitate variable spaced grid. Modified rec…
  cicecore/cicedynB/general/ice_init.F90
  cicecore/cicedynB/infrastructure/ice_grid.F90
  configuration/scripts/cice.batch.csh
  configuration/scripts/ice_in
  configuration/scripts/machines/env.nrlssc_gnu
  configuration/scripts/options/set_nml.scale1
  configuration/scripts/options/set_nml.vargrid
  configuration/scripts/tests/gridsys_suite.ts
  doc/source/user_guide/ug_case_settings.rst
Labels: Type: Feature, Testing, Grids

#754 Update Pull Request Template, add question about updating Icepack
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation

#756 Refactored evp sub cycling loop
  cicecore/cicedynB/dynamics/ice_dyn_evp.F90
Labels: Dynamics

#758 ice_grid: initialize 'l_readCenter' for all grid types
  cicecore/cicedynB/infrastructure/ice_grid.F90
Labels: Type: Bug, Grids
