Repository CICE-Consortium/CICE, pull requests merged in 2022-10, with the labels that each got.

#765 doc: improve "Quick Start" section
  doc/source/intro/quickstart.rst
Labels: Documentation

#764 Refactor strocnxT, strocnyT implementation
  cicecore/cicedynB/dynamics/ice_dyn_eap.F90
  cicecore/cicedynB/dynamics/ice_dyn_evp.F90
  cicecore/cicedynB/dynamics/ice_dyn_vp.F90
  cicecore/cicedynB/general/ice_flux.F90
  cicecore/cicedynB/general/ice_state.F90
  cicecore/cicedynB/general/ice_step_mod.F90
  cicecore/cicedynB/infrastructure/ice_restart_driver.F90
  cicecore/drivers/mct/cesm1/ice_import_export.F90
  cicecore/drivers/mct/cesm1/ice_prescribed_mod.F90
  cicecore/drivers/nuopc/cmeps/ice_import_export.F90
  cicecore/drivers/nuopc/cmeps/ice_prescribed_mod.F90
  cicecore/drivers/nuopc/dmi/cice_cap.info
Labels: Type: Bug, Forcing, Drivers/coupling

#766 ice_init: do broadcast 'default_season'
  cicecore/cicedynB/general/ice_init.F90
Labels: Type: Bug

#769 Correct units in FSD history output
  cicecore/cicedynB/analysis/ice_history_fsd.F90
  doc/source/science_guide/sg_fundvars.rst
Labels: Documentation

#772 Update box test options
  configuration/scripts/options/set_nml.boxclosed
  configuration/scripts/options/set_nml.boxforcee
  configuration/scripts/options/set_nml.boxforcen
  configuration/scripts/options/set_nml.boxforcene
  configuration/scripts/options/set_nml.boxislandsn
  configuration/scripts/options/set_nml.boxislandsne
  configuration/scripts/options/set_nml.boxopen
  configuration/scripts/options/set_nml.boxsymn
  configuration/scripts/options/set_nml.boxsymne
  configuration/scripts/options/set_nml.boxsyms
  configuration/scripts/options/set_nml.boxsymw
  configuration/scripts/options/set_nml.gbox12
  configuration/scripts/options/set_nml.gbox180
  configuration/scripts/options/set_nml.gbox80
  configuration/scripts/tests/cice.results.csh
  configuration/scripts/tests/gridsys_suite.ts
  doc/source/user_guide/ug_implementation.rst
Labels: Testing, Documentation

#771 Update computation of cdn_ocn for use in dynamics
  cicecore/cicedynB/dynamics/ice_dyn_eap.F90
  cicecore/cicedynB/dynamics/ice_dyn_evp.F90
  cicecore/cicedynB/dynamics/ice_dyn_vp.F90
  cicecore/shared/ice_arrays_column.F90
Labels: Type: Bug, Dynamics, Priority: High

#773 Change icetmask to logical consistent with iceumask, icenmask, iceemask
  cicecore/cicedynB/dynamics/ice_dyn_eap.F90
  cicecore/cicedynB/dynamics/ice_dyn_evp.F90
  cicecore/cicedynB/dynamics/ice_dyn_evp_1d.F90
  cicecore/cicedynB/dynamics/ice_dyn_shared.F90
  cicecore/cicedynB/dynamics/ice_dyn_vp.F90
  cicecore/cicedynB/infrastructure/comm/mpi/ice_boundary.F90
  cicecore/cicedynB/infrastructure/comm/serial/ice_boundary.F90
  cicecore/cicedynB/infrastructure/ice_grid.F90
  cicecore/cicedynB/infrastructure/ice_restart_driver.F90
  doc/source/cice_index.rst
  doc/source/user_guide/ug_implementation.rst
Labels: Software Engineering

#774 ice_dyn_vp: allow for bit-for-bit reproducibility under `bfbflag`
  cicecore/cicedynB/dynamics/ice_dyn_vp.F90
  cicecore/cicedynB/general/ice_init.F90
  cicecore/cicedynB/infrastructure/comm/mpi/ice_global_reductions.F90
  cicecore/cicedynB/infrastructure/comm/serial/ice_global_reductions.F90
  cicecore/drivers/unittest/sumchk/sumchk.F90
  configuration/scripts/ice_in
  configuration/scripts/machines/env.ppp5_intel
  configuration/scripts/machines/env.ppp6_gnu
  configuration/scripts/machines/env.ppp6_gnu-impi
  configuration/scripts/machines/env.ppp6_intel
  configuration/scripts/machines/env.ppp6_intel19
  configuration/scripts/machines/env.robert_intel
  configuration/scripts/machines/env.underhill_intel
  doc/source/cice_index.rst
  doc/source/developer_guide/dg_other.rst
  doc/source/science_guide/sg_dynamics.rst
  doc/source/user_guide/ug_case_settings.rst
Labels: Dynamics
