Repository CICE-Consortium/CICE, pull requests merged in 2023-10, with the labels that each got.

#882 Port to perlmutter gnu, intel, cray
  configuration/scripts/cice.batch.csh
  configuration/scripts/cice.launch.csh
  configuration/scripts/machines/Macros.perlmutter_cray
  configuration/scripts/machines/Macros.perlmutter_gnu
  configuration/scripts/machines/Macros.perlmutter_intel
  configuration/scripts/machines/env.perlmutter_cray
  configuration/scripts/machines/env.perlmutter_gnu
  configuration/scripts/machines/env.perlmutter_intel
Labels: Porting

#883 Remove and update tfrz_options settings, remove _old options.
  cicecore/cicedyn/general/ice_init.F90
  configuration/scripts/options/set_nml.alt04
  configuration/scripts/options/set_nml.alt06
  configuration/scripts/options/set_nml.bgcskl
  configuration/scripts/options/set_nml.bgcsklclim
  configuration/scripts/options/set_nml.bgcz
  configuration/scripts/options/set_nml.bgczclim
  configuration/scripts/options/set_nml.bgczm
  configuration/scripts/options/set_nml.boxadv
  configuration/scripts/options/set_nml.boxchan1e
  configuration/scripts/options/set_nml.boxchan1n
  configuration/scripts/tests/baseline.script
  configuration/scripts/tests/omp_suite.ts
Labels: Icepack, Testing

#887 Remove cicedynB link
  cicecore/cicedynB
  doc/source/user_guide/ug_troubleshooting.rst
Labels: Software Engineering

#888 Update Documentation to clarify Namelist Inputs
  doc/source/cice_index.rst
  doc/source/user_guide/ug_case_settings.rst
Labels: Documentation

#889 Update update_ocn_f implementation, Add cpl_frazil namelist
  cicecore/cicedyn/analysis/ice_diagnostics.F90
  cicecore/cicedyn/analysis/ice_history.F90
  cicecore/cicedyn/general/ice_flux.F90
  cicecore/cicedyn/general/ice_init.F90
  cicecore/cicedyn/general/ice_step_mod.F90
  doc/source/cice_index.rst
  doc/source/user_guide/ug_case_settings.rst
Labels: Icepack, Drivers/coupling

#876 Add atm_data_version to allow JRA55 forcing filenames to have a unique version string
  cicecore/cicedyn/general/ice_forcing.F90
  cicecore/cicedyn/general/ice_init.F90
  configuration/scripts/ice_in
  configuration/scripts/options/set_nml.gx1
  configuration/scripts/options/set_nml.gx3
  configuration/scripts/options/set_nml.jra55
  configuration/scripts/options/set_nml.jra55do
  configuration/scripts/options/set_nml.tx1
  doc/source/developer_guide/dg_forcing.rst
  doc/source/user_guide/ug_case_settings.rst
Labels: Forcing

#893 ice_dyn_evp: pass 'grid_location' for LKD seabed stress on C grid
  cicecore/cicedyn/dynamics/ice_dyn_evp.F90
  cicecore/cicedyn/dynamics/ice_dyn_shared.F90
Labels: Type: Bug, Dynamics

#896 Add 5-band dEdd shortwave tests
  configuration/scripts/tests/base_suite.ts
Labels: Icepack, Testing

#898 doc: update histfreq_base and hist_avg descriptions
  doc/source/user_guide/ug_implementation.rst
Labels: Documentation

#900 Revert "Add 5-band dEdd shortwave tests"
  configuration/scripts/tests/base_suite.ts
Labels: Testing

#899 Split N/E grid computation out of Tlonlat, create NElonlat subroutine.
  cicecore/cicedyn/infrastructure/ice_grid.F90
  configuration/scripts/options/set_nml.gx3nc
  configuration/scripts/tests/base_suite.ts
Labels: Type: Bug, Grids

#901 Update version, remove trailing blanks
  cicecore/cicedyn/dynamics/ice_transport_remap.F90
  cicecore/cicedyn/general/ice_forcing.F90
  cicecore/cicedyn/general/ice_init.F90
  cicecore/cicedyn/general/ice_step_mod.F90
  cicecore/drivers/unittest/opticep/ice_step_mod.F90
  cicecore/version.txt
  doc/source/conf.py
Labels: Documentation
