Repository CICE-Consortium/CICE, pull requests merged in 2023-08, with the labels that each got.

#853 Update conda_macos to fix problems with Github Actions testing
  .github/workflows/test-cice.yml
  configuration/scripts/machines/Macros.conda_macos
Labels: Testing, Priority: High

#850 Extend restart output controls, provide multiple frequency options
  cicecore/cicedyn/general/ice_init.F90
  cicecore/cicedyn/infrastructure/io/io_netcdf/ice_restart.F90
  cicecore/cicedyn/infrastructure/io/io_pio2/ice_restart.F90
  cicecore/shared/ice_calendar.F90
  configuration/scripts/ice_in
  configuration/scripts/options/set_nml.histall
  configuration/scripts/options/set_nml.histdbg
  doc/source/cice_index.rst
  doc/source/user_guide/ug_case_settings.rst
  doc/source/user_guide/ug_implementation.rst
Labels: IO

#856 Add logging features to nuopc/cmeps cap; deprecates zsalinity in cap
  cicecore/drivers/nuopc/cmeps/CICE_InitMod.F90
  cicecore/drivers/nuopc/cmeps/CICE_RunMod.F90
  cicecore/drivers/nuopc/cmeps/cice_wrapper_mod.F90
  cicecore/drivers/nuopc/cmeps/ice_comp_nuopc.F90
Labels: Drivers/coupling, IO
