Repository CICE-Consortium/CICE, pull requests merged in 2024-11, with the labels that each got.

#985 Allow kmt variable name of "mask" and different size netcdf 2d reads
  cicecore/cicedyn/infrastructure/ice_grid.F90
  cicecore/cicedyn/infrastructure/ice_read_write.F90
  configuration/scripts/cice.batch.csh
  configuration/scripts/machines/Macros.gadi_intel
  configuration/scripts/tests/base_suite.ts
  doc/source/user_guide/ug_implementation.rst
Labels: Software Engineering, Porting, Grids

#986 Remove orca grid
  cicecore/cicedyn/general/ice_init.F90
  cicecore/cicedyn/infrastructure/ice_domain.F90
  cicecore/cicedyn/infrastructure/ice_grid.F90
  cicecore/cicedyn/infrastructure/ice_read_write.F90
  configuration/scripts/ice_in
  configuration/scripts/tests/base_suite.ts
  doc/source/user_guide/ug_case_settings.rst
Labels: Grids

#991 Add start_tod initialization for nuopc / cmeps driver
  cicecore/drivers/nuopc/cmeps/ice_comp_nuopc.F90
Labels: Drivers/coupling

#995 Add pio_finalize calls for CICE history and restart files
  cicecore/cicedyn/infrastructure/io/io_pio2/ice_history_write.F90
  cicecore/cicedyn/infrastructure/io/io_pio2/ice_pio.F90
  cicecore/cicedyn/infrastructure/io/io_pio2/ice_restart.F90
  configuration/scripts/options/set_nml.histhrly
  configuration/scripts/tests/io_suite.ts
Labels: IO
