Repository CICE-Consortium/CICE, pull requests merged in 2024-02, with the labels that each got.

#931 Update PULL_REQUEST_TEMPLATE to request detailed information
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Type: Process

#934 ug_testing.rst: also mention checking the base suite results
  doc/source/user_guide/ug_testing.rst
Labels: Testing, Documentation

#928 Update IO formats and add new IO namelist controls
  cicecore/cicedyn/analysis/ice_history_shared.F90
  cicecore/cicedyn/general/ice_init.F90
  cicecore/cicedyn/infrastructure/ice_read_write.F90
  cicecore/cicedyn/infrastructure/io/io_netcdf/ice_history_write.F90
  cicecore/cicedyn/infrastructure/io/io_netcdf/ice_restart.F90
  cicecore/cicedyn/infrastructure/io/io_pio2/ice_history_write.F90
  cicecore/cicedyn/infrastructure/io/io_pio2/ice_pio.F90
  cicecore/cicedyn/infrastructure/io/io_pio2/ice_restart.F90
  cicecore/drivers/nuopc/cmeps/ice_comp_nuopc.F90
  cicecore/drivers/standalone/cice/CICE_InitMod.F90
  cicecore/shared/ice_restart_shared.F90
  configuration/scripts/ice_in
  configuration/scripts/machines/env.derecho_cray
  configuration/scripts/machines/env.derecho_gnu
  configuration/scripts/machines/env.derecho_intel
  configuration/scripts/machines/env.derecho_intelclassic
  configuration/scripts/machines/env.derecho_inteloneapi
  configuration/scripts/machines/env.derecho_nvhpc
  configuration/scripts/options/set_env.iopio1p
  configuration/scripts/options/set_env.iopio2p
  configuration/scripts/options/set_nml.iobinary
  configuration/scripts/options/set_nml.iocdf1
  configuration/scripts/options/set_nml.iocdf2
  configuration/scripts/options/set_nml.iocdf5
  configuration/scripts/options/set_nml.iohdf5
  configuration/scripts/options/set_nml.iohdf5opts
  configuration/scripts/options/set_nml.iopio1
  configuration/scripts/options/set_nml.iopio1p
  configuration/scripts/options/set_nml.iopio2
  configuration/scripts/options/set_nml.iopio2p
  configuration/scripts/options/set_nml.iopioopts
  configuration/scripts/options/set_nml.iopnetcdf1
  configuration/scripts/options/set_nml.iopnetcdf2
  configuration/scripts/options/set_nml.iopnetcdf5
  configuration/scripts/tests/io_suite.ts
  doc/source/cice_index.rst
  doc/source/developer_guide/dg_infra.rst
  doc/source/user_guide/ug_case_settings.rst
  doc/source/user_guide/ug_implementation.rst
Labels: IO

#935 io: allow disabling coordinates in history files
  cicecore/cicedyn/analysis/ice_history.F90
  cicecore/cicedyn/analysis/ice_history_shared.F90
  cicecore/cicedyn/infrastructure/io/io_netcdf/ice_history_write.F90
  cicecore/cicedyn/infrastructure/io/io_pio2/ice_history_write.F90
  configuration/scripts/ice_in
Labels: Type: Feature, IO

#936 Set 'idate0' and 'use_leap_years' in nuopc cap
  cicecore/drivers/nuopc/cmeps/ice_comp_nuopc.F90
Labels: Drivers/coupling

#939 Port to Carpenter
  configuration/scripts/cice.batch.csh
  configuration/scripts/cice.launch.csh
  configuration/scripts/machines/Macros.carpenter_cray
  configuration/scripts/machines/Macros.carpenter_gnu
  configuration/scripts/machines/Macros.carpenter_intel
  configuration/scripts/machines/env.carpenter_cray
  configuration/scripts/machines/env.carpenter_gnu
  configuration/scripts/machines/env.carpenter_intel
Labels: Porting
