Repository CICE-Consortium/CICE, pull requests merged in 2024-05, with the labels that each got.

#948 Fix Github Actions for macos system update
  .github/workflows/test-cice.yml
  configuration/scripts/machines/Macros.conda_macos
Labels: Software Engineering, Testing

#947 Standalone gadi (#2)
  configuration/scripts/cice.batch.csh
  configuration/scripts/cice.launch.csh
  configuration/scripts/machines/Macros.gadi_intel
  configuration/scripts/machines/env.gadi_intel
Labels: Porting

#949 Autoset nprocs and improve max_blocks estimate
  cicecore/cicedyn/infrastructure/ice_domain.F90
  cicecore/shared/ice_distribution.F90
  configuration/scripts/ice_in
  doc/source/user_guide/ug_case_settings.rst
Labels: Software Engineering

#953 Update the calculation of uvel and vvel in evp dynamics
  cicecore/cicedyn/dynamics/ice_dyn_evp.F90
  doc/source/science_guide/sg_coupling.rst
  doc/source/science_guide/sg_dynamics.rst
Labels: Dynamics, Documentation

#954 Update the automated max_blocks calculation
  cice.setup
  cicecore/cicedyn/infrastructure/comm/mpi/ice_gather_scatter.F90
  cicecore/cicedyn/infrastructure/comm/serial/ice_gather_scatter.F90
  cicecore/cicedyn/infrastructure/ice_domain.F90
  cicecore/cicedyn/infrastructure/ice_grid.F90
  cicecore/cicedyn/infrastructure/ice_memusage.F90
  cicecore/cicedyn/infrastructure/io/io_binary/ice_restart.F90
  cicecore/shared/ice_distribution.F90
  cicecore/shared/ice_domain_size.F90
  configuration/scripts/cice_decomp.csh
  configuration/scripts/tests/decomp_suite.ts
  configuration/scripts/tests/first_suite.ts
  configuration/scripts/tests/gridsys_suite.ts
  configuration/scripts/tests/perf_suite.ts
  configuration/scripts/tests/unittest_suite.ts
  doc/source/user_guide/ug_case_settings.rst
  doc/source/user_guide/ug_implementation.rst
Labels: Software Engineering, Scripts, Grids

#956 Update Machine Ports, Add CPPs NO_CDF2, NO_CDF5
  cicecore/cicedyn/infrastructure/io/io_netcdf/ice_history_write.F90
  cicecore/cicedyn/infrastructure/io/io_netcdf/ice_restart.F90
  configuration/scripts/machines/Macros.compy_intel
  configuration/scripts/machines/Macros.gaffney_gnu
  configuration/scripts/machines/Macros.gaffney_intel
  configuration/scripts/machines/Macros.koehr_intel
  configuration/scripts/machines/Macros.mustang_intel18
  configuration/scripts/machines/Macros.mustang_intel19
  configuration/scripts/machines/Macros.mustang_intel20
  configuration/scripts/machines/env.hera_intel
  doc/source/user_guide/ug_case_settings.rst
  doc/source/user_guide/ug_implementation.rst
  doc/source/user_guide/ug_running.rst
Labels: Testing, Porting
