Repository CICE-Consortium/CICE, pull requests merged in 2025-05, with the labels that each got.

#1019 Port to blueback
  configuration/scripts/cice.batch.csh
  configuration/scripts/cice.launch.csh
  configuration/scripts/machines/Macros.blueback_aocc
  configuration/scripts/machines/Macros.blueback_cray
  configuration/scripts/machines/Macros.blueback_gnu
  configuration/scripts/machines/Macros.blueback_intel
  configuration/scripts/machines/Macros.blueback_nvhpc
  configuration/scripts/machines/env.blueback_aocc
  configuration/scripts/machines/env.blueback_cray
  configuration/scripts/machines/env.blueback_gnu
  configuration/scripts/machines/env.blueback_intel
  configuration/scripts/machines/env.blueback_nvhpc
Labels: Porting

#1021 Update blueback for automated testing
  configuration/scripts/machines/env.blueback_aocc
  configuration/scripts/machines/env.blueback_cray
  configuration/scripts/machines/env.blueback_gnu
  configuration/scripts/machines/env.blueback_intel
  configuration/scripts/machines/env.blueback_nvhpc
Labels: Porting

#1023 Use ymd instead of uninitialized date in timeInit for (unused?) optDate in alarmInit
  cicecore/drivers/nuopc/cmeps/ice_shr_methods.F90
Labels: Drivers/coupling

#1025 Update job completion checking associated with testing
  configuration/scripts/tests/poll_queue.csh
Labels: Testing, Scripts

#1027 updates to distribution policy and zenodo template
  .zenodo.json
  DistributionPolicy.pdf
Labels: Documentation, Type: Process

#1028 Update set_version_number.csh to update .zenodo.json file
  configuration/scripts/set_version_number.csh
Labels: Documentation

#1030 updates to LANL/Triad copyright and license
  COPYRIGHT.pdf
  LICENSE.pdf
  cicecore/drivers/direct/hadgem3/CICE.F90
  cicecore/drivers/mct/cesm1/CICE_copyright.txt
  cicecore/drivers/nuopc/cmeps/CICE_copyright.txt
  cicecore/drivers/nuopc/dmi/CICE.F90
  cicecore/drivers/standalone/cice/CICE.F90
  doc/source/conf.py
  doc/source/intro/copyright.rst
  doc/source/user_guide/ug_implementation.rst
Labels: Documentation
