Repository CICE-Consortium/CICE, pull requests merged in 2025-07, with the labels that each got.

#1020 Template for sealevelponds CICE changes
  cicecore/cicedyn/analysis/ice_history_pond.F90
  cicecore/cicedyn/dynamics/ice_transport_driver.F90
  cicecore/cicedyn/general/ice_flux.F90
  cicecore/cicedyn/general/ice_init.F90
  cicecore/cicedyn/general/ice_step_mod.F90
  cicecore/cicedyn/infrastructure/io/io_netcdf/ice_restart.F90
  cicecore/cicedyn/infrastructure/io/io_pio2/ice_restart.F90
  cicecore/drivers/nuopc/cmeps/CICE_InitMod.F90
  cicecore/drivers/nuopc/cmeps/CICE_RunMod.F90
  cicecore/drivers/standalone/cice/CICE_InitMod.F90
  cicecore/drivers/standalone/cice/CICE_RunMod.F90
  cicecore/shared/ice_init_column.F90
  cicecore/shared/ice_restart_column.F90
  configuration/scripts/ice_in
  configuration/scripts/options/set_nml.pondsealvl
  configuration/scripts/tests/base_suite.ts
Labels: Icepack

#1039 running quick_suite on ursa
  configuration/scripts/cice.batch.csh
  configuration/scripts/cice.launch.csh
  configuration/scripts/machines/Macros.ursa_intel
  configuration/scripts/machines/env.ursa_intel
Labels: Porting

#1042 Update json template
  .zenodo.json
Labels: Scripts
